	name: Bug Report
	description: Create a report to help me improve this engine
	labels: ["🐞 Bug"]
	assignees:
	  - BlyZeYT
	body:
	  - type: textarea
	    id: error
	    attributes:
	      label: Error
	      description: Specify the error
	    validations:
	      required: false
	  - type: textarea
	    id: what-happened
	    attributes:
	      label: What happened?
	      description: Describe as detailed as possible.
	      placeholder: Also tell me, what did you expect to happen?
	      value: "Steps to reproduce:\n\n1. Use this...\n2. Then do this...\n3. Error happens!"
	    validations:
	      required: true
	  - type: textarea
	    id: version
	    attributes:
	      label: Version
	      description: What version of ConsoleNexus Engine are you using?
	      placeholder: For example: 1.0.0.0
	    validations:
	      required: true
	  - type: checkboxes
	    id: windows
	    attributes:
	      label: Windows Version
	      description: On which windows version(s) do you have the problem?
	      options:
	        - label: Windows 11
	        - label: Windows 10
	        - label: Windows 8
	        - label: Windows 7
		- label: Older
	    validations:
	      required: true
	  - type: textarea
	    id: additional
	    attributes:
	      label: Additional context
	      description: Any other context that could be useful
	    validations:
	      required: false
